a = input('Digite algo =')
print('O tipo primitivo é', type(a))
print('O tipo é somente espaço', a.isspace())
print('É um número', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alfanúmerico?', a.isalnum())
print('Está em maiúscula?', a.isupper())
print('Está em minúscula?', a.islower())
print('Está capitalizada?', a.istitle())
